### ISSUE TITLE
If a player disconnect from the server and fast logged in back, the player are allready exist on the server, we need a check for this behaviour

### ISSUE THREAD

**Issue by Assambra** [Assambra/Free-MMORPG#45]

**Comment by tvd12** [comment]
You can have a reconnect flow like that:

1. After an user access app, you don't send a game logic command from client, instead of you will send a reconnect command [like this](https://github.com/tvd12/space-shooter/blob/master/unity/Assets/Done/Scripts/SocketClientProxy.cs#L65)
2. On server you will check state of the user and response the reconnect response [like this](https://github.com/tvd12/space-shooter/blob/master/server-java/src/main/java/com/tvd12/space_shooter/controller/UserRequestController.java#L92)

**Comment by Assambra** [comment]
We close this issue because we open a new issue here #83 with the instructions how to implement a reconnecting it match better as the original issue descriped here. And at the moment it isnt reproducable too.
